//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend_minimarket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int fac_id { get; set; }
        public int pedido_pe_id { get; set; }
        public string ruc { get; set; }
        public string razon_social { get; set; }
        public string nums_erie { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime hora { get; set; }
        public bool flag_cancelado { get; set; }
        public decimal igv { get; set; }
        public decimal importe_total { get; set; }
        public decimal operacion_grabada { get; set; }
    
        public virtual pedido pedido { get; set; }
    }
}
