//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend_minimarket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class modo_pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modo_pago()
        {
            this.pedido = new HashSet<pedido>();
        }
    
        public int modo_id { get; set; }
        public string nombre { get; set; }
        public string nombre_titular { get; set; }
        public int tarjeta_numero { get; set; }
        public int cvv { get; set; }
        public System.DateTime fecha_cad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
    }
}
