//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend_minimarket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido()
        {
            this.boleta = new HashSet<boleta>();
            this.detalle_pedido = new HashSet<detalle_pedido>();
            this.factura = new HashSet<factura>();
        }
    
        public int pe_id { get; set; }
        public System.DateTime pe_Fecha { get; set; }
        public System.TimeSpan pe_hora { get; set; }
        public int pe_idUsuario { get; set; }
        public decimal pe_Monto { get; set; }
        public int pe_idModoPago { get; set; }
        public bool pe_Anular { get; set; }
        public bool pe_Estado { get; set; }
        public int modo_pago_modo_id { get; set; }
        public int usuario_u_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boleta> boleta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_pedido> detalle_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
        public virtual modo_pago modo_pago { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
