//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend_minimarket.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.pedido = new HashSet<pedido>();
        }
    
        public int u_id { get; set; }
        public string u_dni { get; set; }
        public string u_nombres { get; set; }
        public string u_apellidoPaterno { get; set; }
        public string u_apellidoMaterno { get; set; }
        public System.DateTime u_fechaNac { get; set; }
        public string u_direccion { get; set; }
        public string u_telefono { get; set; }
        public string u_correo { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public bool u_estado { get; set; }
        public int rol_rol_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido> pedido { get; set; }
        public virtual rol rol { get; set; }
    }
}
